## Amazon Products Review

### Objective

The goal of this project is to clean and prepare a deliberately messy Amazon products and reviews dataset for reliable analysis. The dataset contains missing values, duplicate records, inconsistent formatting, invalid numerical values, datatype issues, and other data-quality problems.

The cleaning process will involve identifying these issues, deciding how each one should be handled, applying the necessary corrections, and comparing the dataset before and after cleaning.

In [1]:
#importing libraries
import numpy as np
import pandas as pd

In [2]:
#importing dataset
amazon_data = pd.read_excel('Amazon_Products_Reviews_Dataset_UNCLEANED.xlsx')

In [3]:
#creating a copy of the dataset
amazon_data_copy = amazon_data.copy()

## Data Inspection
I first inspected the dataset to understand its structure and to identify any obvious data-quality issues before making changes. This includes checking the number of rows and columns, missing values, duplicate records, and the current data types of the columns.

In [4]:
amazon_data.head()

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,B08SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,B07F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,B08TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,B08GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...

In [5]:
amazon_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1479 non-null   object
 1   product_name            1476 non-null   object
 2   category                1473 non-null   object
 3   Discounted_Price (INR)  1473 non-null   object
 4   actual_price            1473 non-null   object
 5   discount_percentage     1473 non-null   object
 6   rating                  1470 non-null   object
 7   Rating Count            1468 non-null   object
 8   about_product           1473 non-null   object
 9   user_id                 1487 non-null   object
 10  user_name               1486 non-null   object
 11  review_id               1487 non-null   object
 12  review_title            1481 non-null   object
 13  review_content          1483 non-null   object
 14  IMG_LINK                1476 non-null   object
 15  product_link            1476 non-null   object
dtypes: object(16)
memory usage: 187.0+ KB

In [6]:
amazon_data.describe()

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
count,1479,1476,1473,1473,1473,1473,1470,1468,1473,1487,1486,1487,1481,1483,1476,1476
unique,1350,1346,260,610,520,141,32,1138,1289,1199,1204,1194,1192,1214,1406,1454
top,B08DDRGWTJ,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,60%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/31XO-wfGGG...,https://www.amazon.in/Atomberg-Renesa-Motor-Re...
freq,4,5,222,54,111,56,245,9,5,10,10,10,10,8,3,2

In [7]:
amazon_data.shape

(1495, 16)

In [8]:
amazon_data.columns

Index(['product_id', 'product_name', 'category', 'Discounted_Price (INR)',
       'actual_price', 'discount_percentage', 'rating', 'Rating Count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'IMG_LINK ', 'product_link'],
      dtype='object')

### Data Quality Check
firstly, i would create a baseline of the dataset to compare before/after data cleaning.

These checks include missing values, duplicate records, completely blank rows, and data types. Numerical columns will also be examined for invalid or unusual values before any corrections are made.

In [9]:
# The original dataset condition is been recorded before making any cleaning changes
before_rows = len(amazon_data)
before_nulls = amazon_data.isna().sum().sum()
before_duplicates = amazon_data.duplicated().sum()
before_blank_rows = amazon_data.isna().all(axis=1).sum()

### Missing Value Check

I checked each column for missing values to determine where there is an incomplete information. The number and percentage of missing values will help determine the most appropriate treatment for each affected column.

In [10]:
missing_report = pd.DataFrame({
    "Null Count": amazon_data.isna().sum(),
    "Null Percentage": (amazon_data.isna().sum() / len(amazon_data) * 100).round(2)
})

missing_report

                        Null Count  Null Percentage
product_id                      16             1.07
product_name                    19             1.27
category                        22             1.47
Discounted_Price (INR)          22             1.47
actual_price                    22             1.47
discount_percentage             22             1.47
rating                          25             1.67
Rating Count                    27             1.81
about_product                   22             1.47
user_id                          8             0.54
user_name                        9             0.60
review_id                        8             0.54
review_title                    14             0.94
review_content                  12             0.80
IMG_LINK                        19             1.27
product_link                    19             1.27

### Duplicate Check

I checked for exact duplicate rows before making any changes to the dataset. Duplicate records can cause the same product information to be counted more than once, so they need to be identified before the cleaning process begins.

In [11]:
amazon_data.duplicated().sum()

np.int64(13)

In [12]:
amazon_data[amazon_data.duplicated()]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
294,B09XXZXQC1,Xiaomi Pad 5| Qualcomm Snapdragon 860| 120Hz R...,Computers&Accessories|Tablets,"₹26,999","₹37,999",29%,4.6,"2,886",Qualcomm Snapdragon 860 Octa-core processor | ...,"AGIQYUS55MG4UWXTEF4PRMPZWPQA,AH4VWAKSTYSTM4XW5...","& I Am IronMan,Amazon Customer,Sayandeep Sarka...","R2BT60BZIDC986,R17KDJGM0QOT3P,R2U9CP6B4FEVBN,R...",the only ANDROID tablet that makes sense in th...,first i would like to comment on the tab marke...,https://m.media-amazon.com/images/I/31jUKdJdjH...,https://www.amazon.in/Snapdragon-Resolution-Re...
488,B0856HY85J,boAt Rockerz 550 Over Ear Bluetooth Headphones...,"Electronics|Headphones,Earbuds&Accessories|Hea...","₹1,799","₹4,999",64%,4.1,"55,192",Tap into instant wireless connectivity with th...,"AEKZNJLC7X57UF3F4STP3GSIIGJA,AGPESHJAGFFNOORA7...","Ananthu,Dheeraj Krishnan,Rani D.,Nasim,Anupma ...","R16XVVFYUNVL5L,R2MGT9GPFEHTPY,R326AAFTL0LMUL,R...","Good but check the below mentioned things,Goin...",The product was received without damaged and s...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boat-Rockerz-550-Headpho...
507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
652,B00V9NHDI4,Eureka Forbes Trendy Zip 1000 Watts powerful s...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...","₹2,799","₹3,799",26%,3.9,"32,931",Post Purchase virtual Demo is provided on this...,"AGOKX4THWIRFYRMYQ5KFQHJZFBLQ,AEQEI4TU3C6Z3PCZ4...","vaneesha,Priyabrata Mallick,Parag Kane,Prabalj...","R3DIC1PKBZ9GQG,RWMXE334TZ0PH,R39LOZ2XWCT0YP,R3...","Decent product,Handy and easy to use,Good prod...",Its not a very great procut if u r looking for...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Trendy-Zip...
781,B09LV1CMGH,"Lifelong LLFH921 Regalia 2000 W Fan Heater, 3 ...","Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...",₹899,"₹2,000",55%,3.6,291,Meant for Spot Heating|Ideal for a small room ...,"AGWW6QNDSOJD7QJMPIUX6ARHJNYQ,AGBTCEQQM6J6NFR5S...","Usha,CHHATRPAL,Anurag Anand,Sijo Pattam,Guruje...","R2GKWK7SWXRZHR,R3ME9LEM264R7O,R2B4QC6Z8AM7H1,R...","For medium sized room,Best product,For bed onl...",",Nice blower,Not heating full room, only bed,P...",https://images-na.ssl-images-amazon.com/images...,https://www.amazon.in/Lifelong-LLFH921-Overhea...
830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1214,B09LV13JFB,LOHAYA Voice Assistant Remote Compatible for A...,"Electronics|HomeTheater,TV&Video|Accessories|R...",₹399,₹999,60%,3.3,23,100% Best Quality Plastic Body and Soft Silico...,"AERUC72DWRPOM2EHX3YBTBPKYV7A,AHMH6RNLYI2G65HY7...","Amazon Customer,Amazon Customer,Akul,Akash Yad...","R1P2VLNHZAHSCU,R28B2GC0X0RMKW,RQ2S0N0NGDQVY,R1...",When I placed the order I was in doubt whether...,"Ok,Very disappointedRange is not good it doesn...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/LOHAYA-Assistant-Compati...
1411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1431,B01FSYQ2A4,boAt Rockerz 400 Bluetooth On Ear Headphones W...,"Electronics|Headphones,Earbuds&Accessories|Hea...","₹1,399","₹2,990",53%,4.1,"97,174",With 40mm Drivers get ready to immerse in HD a...,"AFWOX5BA5QS5TCVTNV3EHQXOSCLQ,AGGM4C652EG6WSDEO...","Sagar,Shreyas,Arjun Thomas,Sachin Yadav,Karthi...","R2E3GV1LFGQNFD,R3IM6TBVGY4SYQ,R236B8Q3BSGZJ7,R...","Worth Every Square Inch.,VFM, Plastic build. M...",----------------------------------------------...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Super-Rockerz-400-Blueto...

### Blank Rows Check

The dataset description indicates that a few completely blank rows may be present. I checked for rows where every column is missing so that these records can be handled separately from rows that contain useful information but have only some missing fields.

In [13]:
# Count rows where every column is missing
blank_rows = amazon_data.isna().all(axis=1).sum()

blank_rows

np.int64(8)

In [14]:
amazon_data[amazon_data.isna().all(axis=1)]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# Remove the visible price formatting so the values can be checked numerically
price_check = pd.to_numeric(
    amazon_data["Discounted_Price (INR)"]
    .astype("string")
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip(),
    errors="coerce"
)

# Find non-missing price entries that could not be converted into numbers
unparsed_price = amazon_data.loc[
    amazon_data["Discounted_Price (INR)"].notna() &
    price_check.isna(),
    "Discounted_Price (INR)"
]

unparsed_price

227    3657.66.00
Name: Discounted_Price (INR), dtype: object

In [16]:
amazon_data["Discounted_Price (INR)"].value_counts(dropna=False).head()

Discounted_Price (INR)
₹199    54
₹299    44
₹399    35
₹499    31
₹349    28
Name: count, dtype: int64

In [17]:
amazon_data["actual_price"].value_counts(dropna=False).head()

actual_price
₹999      111
₹499       68
₹1,999     55
₹1,499     33
₹399       32
Name: count, dtype: int64

In [18]:
amazon_data["discount_percentage"].value_counts(dropna=False).head()

discount_percentage
60%    56
50%    51
0%     43
80%    37
55%    36
Name: count, dtype: int64

In [19]:
amazon_data["rating"].value_counts(dropna=False)

rating
4.1    245
4.3    231
4.2    225
4.0    128
4.4    123
3.9    122
3.8     81
4.5     73
4       50
3.7     43
3.6     36
3.5     26
NaN     25
4.6     18
3.3     17
3.4     10
4.7      6
6.0      5
3.1      4
-1       4
5.0      3
3.0      3
5.5      3
2.8      2
4.8      2
New      2
3.2      2
|        1
2.3      1
2        1
3        1
2.6      1
2.9      1
Name: count, dtype: int64

In [20]:
amazon_data["Rating Count"].value_counts(dropna=False).head()

Rating Count
NaN                   27
9,378                  9
18,998                 8
Not enough ratings     8
24,269                 7
Name: count, dtype: int64

### Data Quality Findings

The inspection revealed several problems that need to be worked on during cleaning. Missing values are present across all 16 columns, with the highest percentage occurring in "Rating Count".

The dataset also contains 8 completely blank rows and repeated product records. Also, there were several fields that should contain numerical information are currently stored as text, as shown by the "object" datatype reported during the inspection.

Further inspection of the numerical-related fields revealed formatting and validity issues, particularly in "rating", "discount_percentage", "Discounted_Price (INR)", "actual_price", and "Rating Count". These columns will require additional cleaning before their data types can be corrected.

In [21]:
amazon_data["category"].value_counts(dropna=False).head()

category
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables    222
Electronics|WearableTechnology|SmartWatches                                           72
Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones                  66
Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions                         59
Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear                          50
Name: count, dtype: int64

In [22]:
amazon_data["product_id"].value_counts(dropna=False).head()

product_id
NaN           16
B08DDRGWTJ     4
B077Z65HSD     4
B07XLCFSSN     3
B082T6V3DT     3
Name: count, dtype: int64

In [23]:
amazon_data["IMG_LINK "].head()

0    https://m.media-amazon.com/images/I/51J45Dcgkt...
1    https://m.media-amazon.com/images/W/WEBP_40237...
2    https://m.media-amazon.com/images/I/41yrqUum9E...
3    https://m.media-amazon.com/images/W/WEBP_40237...
4    https://m.media-amazon.com/images/I/31-XtyZy0I...
Name: IMG_LINK , dtype: object

In [24]:
amazon_data["product_link"].head()

0    https://www.amazon.in/boAt-Stone-250-Playback-...
1    https://www.amazon.in/Eureka-Forbes-Euroclean-...
2    https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3    https://www.amazon.in/Logitech-Silent-Wireless...
4    https://www.amazon.in/Havells-Instanio-Storage...
Name: product_link, dtype: object

In [25]:
amazon_data["product_link"].dropna().str.startswith("https://").value_counts()

product_link
True     1447
False      29
Name: count, dtype: int64

In [26]:
amazon_data["IMG_LINK "].dropna().str.startswith("https://").value_counts()

IMG_LINK
True     1447
False      29
Name: count, dtype: int64

In [27]:
# Show examples of product links that do not start with https://
# Check the non-missing product links that do not start with https://
product_links = amazon_data["product_link"].dropna()

product_links[~product_links.str.startswith("https://")].head()

11     www.amazon.in/Zebronics-Zeb-County-Bluetooth-S...
17     www.amazon.in/Samsung-Mystique-Storage-Purchas...
63     www.amazon.in/Acer-inches-Ready-AR32NSV53HD-Bl...
150    www.amazon.in/Bajaj-Waterproof-Watts-Immersion...
163    www.amazon.in/AmazonBasics-Nylon-Braided-Light...
Name: product_link, dtype: object

In [28]:
# Show examples of image links that do not start with https://
# Check the non-missing product links that do not start with https://
image_links = amazon_data["IMG_LINK "].dropna()

image_links[~image_links.str.startswith("https://")].head()

224    m.media-amazon.com/images/I/41yPeG8kXxL._SX300...
302    m.media-amazon.com/images/I/41gQbaGlXrL._SX300...
321    m.media-amazon.com/images/I/41IcuNkyrdL._SX300...
367    m.media-amazon.com/images/I/51DLLa8HNWL._SX300...
378    m.media-amazon.com/images/I/51ucu0nCeSL._SX300...
Name: IMG_LINK , dtype: object

In [29]:
# Check whether the flagged links contain any URL protocol at all
bad_product_links = product_links[
    ~product_links.str.startswith(("http://", "https://"))]

bad_product_links.str.contains("://", regex=False).value_counts()

product_link
False    29
Name: count, dtype: int64

In [30]:
# Check whether the links missing https:// start with www.
bad_product_links = product_links[
    ~product_links.str.startswith("https://")]

bad_product_links.str.startswith("www.").value_counts()

product_link
True    29
Name: count, dtype: int64

In [31]:
# Check whether the links missing https:// start with the Amazon image domain
bad_image_links = image_links[
    ~image_links.str.startswith("https://")]

bad_image_links.str.startswith("m.media-amazon.com").value_counts()

IMG_LINK
True    29
Name: count, dtype: int64

### URL Standardisation Finding

The URL check found 29 non-missing values in both "product_link" and "IMG_LINK" that did not include the "https://" scheme.

The values still contain recognizable Amazon domains, such as "www.amazon.in" for product links and "m.media-amazon.com" for image links. Since the issue is the missing protocol rather than a missing destination, these values can be standardised by adding "https://" rather than removing the records.

In [32]:
# Remove the visible price formatting so the values can be checked numerically
price_check = pd.to_numeric(
    amazon_data["Discounted_Price (INR)"]
    .astype("string")
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip(),
    errors="coerce"
)

In [33]:
price_check.head()

0    1199.0
1     253.0
2    1099.0
3      <NA>
4    6990.0
Name: Discounted_Price (INR), dtype: Float64

In [34]:
price_check.describe()

count         1472.0
mean     3103.349708
std      7051.692579
min         -27900.0
25%            299.0
50%            799.0
75%           1999.0
max          77990.0
Name: Discounted_Price (INR), dtype: Float64

In [35]:
(price_check <= 0).sum()

np.int64(13)

In [36]:
price_check[price_check <= 0]

13          0.0
183         0.0
365      -399.0
539     -1499.0
947      -325.0
1020        0.0
1079        0.0
1088     -828.0
1133     -999.0
1213     -299.0
1237        0.0
1313     -999.0
1325   -27900.0
Name: Discounted_Price (INR), dtype: Float64

In [37]:
# Remove the % sign so the discount values can be checked as numbers
discount_check = pd.to_numeric(
    amazon_data["discount_percentage"]
    .astype("string")
    .str.replace("%", "", regex=False)
    .str.strip(),
    errors="coerce"
)

In [38]:
((discount_check < 0) | (discount_check > 100)).sum()

np.int64(8)

In [39]:
discount_check[
    (discount_check < 0) | (discount_check > 100)
]

476     120
647     120
766     120
779     120
807     120
996     150
1227    150
1380    -15
Name: discount_percentage, dtype: Int64

### Value Range and Formatting Findings

The numerical-related fields also contain several values that need to be corrected before the data can be used reliably.

The discounted price column contains 13 zero or negative values, including several negative prices. These values do not represent valid product prices and will need to be treated as invalid during cleaning.

The discount percentage column contains 8 values outside the expected 0–100 range. These include values of 120%, 150%, and -15%, which cannot be treated as valid discounts.

The rating column also contains values outside the expected 1–5 range, along with non-numeric placeholders such as "New" and "|".

In addition to these range issues, the price and discount columns are stored as text and contain formatting such as currency symbols and percentage signs. These formatting issues will be standardised before the final data types are assigned.

## Missing Data Handling

### Removing Completely Blank Rows

The initial inspection identified 8 rows in which every column was missing. Since these rows contain no product or review information at all, there is nothing meaningful to recover through imputation.

I therefore removed these completely blank records before dealing with the remaining missing values. This also prevents the blank rows from affecting the duplicate count.

In [40]:
# Count the blank rows before removing them
blank_rows_removed = amazon_data_copy.isna().all(axis=1).sum()

amazon_data_copy = amazon_data_copy.dropna(how="all").copy()

blank_rows_removed

np.int64(8)

In [41]:
amazon_data_copy.dropna(how="all")

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
0,B08SMJT55F,boAt Stone 250 Portable Wireless Speaker with ...,Electronics|HomeAudio|Speakers|BluetoothSpeakers,"₹1,199","₹3,990",70%,4.2,"2,908",Power- Get ready to be enthralled by the 5W RM...,"AHL435VQHZZXB545DXGLIZSACFOQ,AG6OEN75DD6ADCNOY...","Devashish Gautam,Vishakha,Sunny Tanna,Dr.Suman...","RLXE2MCKLCYMB,R39DFUZXNDFQ4,R30U7W2G83AI48,R2X...","Strudy, Awesome connectivity........but bass i...",The LED light is vibrant with multiple form se...,https://m.media-amazon.com/images/I/51J45Dcgkt...,https://www.amazon.in/boAt-Stone-250-Playback-...
1,B07F6GXNPB,EUREKA FORBES EUROCLEAN PAPER VACUUM CLEANER D...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cl...",₹253,₹500,49%,4.3,"2,664",Special Anti-Microbial(Biocide Treated) Paper ...,"AEAHCVLMYLKLICSIKCTUS54NVQ2A,AFRIWQJKFSDZKTRTU...","Lulzdrone,KRISH,Harsh Shah,Harsh,HaPa,Inderjee...","R2K8VZSTF6Y1UH,R30LKPXEPE0CZE,R2714DP5UNSOQ,R1...","Bigger size,Superb.,Vacuum Bag,Price is reason...",These are the biggest one their models use and...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Eureka-Forbes-Euroclean-...
2,B08TTRVWKY,MILTON Smart Egg Boiler 360-Watts (Transparent...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹1,099","₹1,899",42%,4.3,"1,811",3 Boiling Modes - The advanced appliance from ...,"AH2NLR3ZG7SADP6RTRU5PDZUBKYQ,AEDHYDNNCKCAOWK4...","Tapan Dutta,Seerat Dar,Saravana Kumar K N,Prad...","R1SPFVN2778DYH,R2GUT54B310MIN,R2WBP8YTLS3OPJ,R...","Nice good,Easy to use,Good , however little co...","Like it,Awesome product 😊,Follow the instructi...",https://m.media-amazon.com/images/I/41yrqUum9E...,https://www.amazon.in/MILTON-Smart-Egg-Boiler-...
3,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,NaN,"₹1,645",21%,4.6,"12,375",Quieter Click: Logitech’s SilentTouch Technolo...,"AE6TTPY5R4YW3XHTPGX6CGHLMVGA,AG5CBSM4UJ7KPPFIQ...","Awesome Shopper,Suresh madaka,Amazon Customer,...","R17S7JVWFH1X6W,R1HINIS5AG6PXD,R3VZFLZVFVZ13G,R...","Good but the scroll is now damaged,Nice,Noisel...",- excellent piece of wireless mouse- reasonabl...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Logitech-Silent-Wireless...
4,B08GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,"₹6,990","₹14,290",51%,4.4,"1,771",Suitable for high-rise buildings and pressure ...,"AGUM6DLWGQ2LOM4MCKXEXKBXHXCQ,AELFZZK6GYFN3YA6T...","Amazon Customer,Gaurav,khalil shaikh,Aman Seti...","R3N1KWPD82KCJH,RUP7RE9R1GMG7,R1EM1ELIZK4UQO,R1...",Good product but attention needed in packing a...,"For this price range product design, look, spe...",https://m.media-amazon.com/images/I/31-XtyZy0I...,https://www.amazon.in/Havells-Instanio-Storage...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,B0756K5DYZ,Prestige Iris 750 Watt Mixer Grinder with 3 St...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹3,249","₹6,295",48%,3.9,"43,070",Motor Warranty: 2; Product Warranty: 2;|Operat...,"AENY7MQ3WUVPIJ5I5GPDPMC3NKPA,AGUCURUVW2ZY4B5WL...","Prabhat,Chandrika,Pramesh969,Prity,Amit Kumar,...","R4FRMNYYMSIBC,R3L7S5SH36JCUJ,R1YN1N7YNW7AIJ,RF...","Juicer is not effective,Ok good,Products quali...","Juicer is not effective,Ok good,https://m.medi...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Prestige-Iris-Grinder-St...
1491,B01LY9W8AF,"Cello Eliza Plastic Laundry Bag/Basket, 50 lit...",Home&Kitchen|HomeStorage&Organization|LaundryO...,₹998.06,"₹1,282",22%,4.2,"7,274","Material: Plastic, Color: Light Grey100% food ...","AFUIW75M2VCMJ2RAD5HFEUHXCRKA,AFWO26UIM72Q7ZPHS...","Amit Singh,RN,Madhuri,SHUKDEB P.,Mano,Harsha,m...","R3ORPP4CPI5V9S,R2M6DE07UL43TF,R37BE8EXG1TX8H,R...","Nice product,Ok,The lid could be more sturdier...",It's a good product for strong daily laundry c...,https://m.media-amazon.com/images/I/51CyJ9dUiW...,https://www.amazon.in/Plastic-Laundry-Basket-L...
1492,B091JF2TFD,Boult Audio BassBuds Oak in-Ear Wired Earphone...,"Electronics|Headphones,Earbuds&Accessories|Hea...",₹499,"₹1,299",62%,3.9,"1,173","In-line Controls: Answer/reject/ calls, play/p...","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4C...","Kulasekaranslrk,Amazon Customer,Sampada,Rudrak...","R3BZHVNU56YYR,R3JMZ9FQ4EE6ZQ,RCREBFSXZQ9JF,R1L...","Does its job for the price,Not for music but c...",A peculiar product in the market. Good sound q...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Boult-Audio-BassBuds-Oak...
1493,B0B3JSWG81,NGI Store 2 Pieces Pet Hair Removers for Your ...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",₹199,₹999,80%,3.1,2,"Versatile, Protects Your Clothes: MoveCatcher ...",AFPKVN5KLHB4MHSYDS25Q5MIWWKQ,Kunal Sen,R18OKMWGX8SA0L,Useless,Does not work as advertised at all. The pieces...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Hair-Removers-Laundry-Re...
1494,B00PVT30YI,Kitchen Mart Stainless Steel South Indian Filt...,"Home&Kitchen|Kitchen&HomeAppliances|Coffee,Tea...",₹292,₹499,41%,4.1,"4,238",Material: Food Grade stainless steel; Make aut...,"AFUYYV4MJWXM6FKQL6BR44OK52GA,AE5N2V2V7NEXSAKNO...","Amazon Customer,meena polkam,Amazon Customer,N...","R2UUBE6SD6DQ9Y,RYT31I1KBXJ0V,R4JW61N9AEDHA,R2D...","Coffee Filter,Just go for it!,Happy with the p...",Coffee Filter is just the right size for a sma...,NaN,https://www.amazon.in/Kitchen-Stainless-Indian...

In [42]:
amazon_data_copy.isna().all(axis=1).sum()

np.int64(0)

In [43]:
amazon_data_copy.duplicated().sum()

np.int64(6)

In [44]:
# Store the duplicate count before removing the repeated records
duplicates_removed = amazon_data_copy.duplicated().sum()

amazon_data_copy = amazon_data_copy.drop_duplicates().copy()

duplicates_removed

np.int64(6)

In [45]:
amazon_data_copy.duplicated().sum()

np.int64(0)

### Duplicate Removal

After removing the completely blank rows, I checked the remaining dataset for exact duplicate records. This was done separately so that the repeated blank rows would not be mixed with genuine duplicated product records.

The exact duplicate product records were then removed, keeping the first occurrence of each record. The number of records removed was recorded so that the change can be included in the final before-and-after summary.

In [46]:
unparsed_price = amazon_data.loc[
    amazon_data["Discounted_Price (INR)"].notna() &
    price_check.isna(),
    "Discounted_Price (INR)"
]

unparsed_price

227    3657.66.00
Name: Discounted_Price (INR), dtype: object

In [47]:
actual_price_check = pd.to_numeric(
    amazon_data["actual_price"]
    .astype("string")
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip(),
    errors="coerce"
)

(actual_price_check <= 0).sum()

np.int64(13)

In [48]:
actual_price_check[actual_price_check <= 0]

100      -499.0
331         0.0
583         0.0
753         0.0
787      -350.0
893    -20990.0
1046    -1999.0
1187        0.0
1231        0.0
1309    -4200.0
1335    -2999.0
1361   -12150.0
1448    -2500.0
Name: actual_price, dtype: Float64

### Data Quality Report Summary

The initial assessment showed that the dataset contains several types of data-quality issues. There are missing values across all 16 columns, along with 8 completely blank rows and repeated records.

The numerical-related fields also require attention. Both price columns contain zero or negative values, the discounted price column includes one malformed value (3657.66.00), and the discount column contains values outside the valid 0–100% range. The rating column also contains values outside the expected 1–5 range as well as non-numeric placeholders.

Formatting issues were also found in the URL fields, where 29 non-missing values in each URL column are missing the "https://" scheme. In addition, one column name contains an unwanted trailing space.

These findings provide the basis for the cleaning decisions that will be applied to the copied dataset.

## Data Standardisation

The initial checks showed that several columns contain values that are stored in inconsistent formats. Before correcting the final data types or handling the remaining missing values, I will standardise these fields first.

This includes cleaning the price and discount formats, dealing with non-standard rating and rating-count entries, correcting the column name with the extra space, and fixing the missing URL scheme where the underlying link is still identifiable.

I will make these changes on the copied dataset so that the original raw data remains available for comparison.

In [49]:
# Remove the extra space from the image-link column name
amazon_data_copy.columns = amazon_data_copy.columns.str.strip()

In [50]:
amazon_data_copy.columns

Index(['product_id', 'product_name', 'category', 'Discounted_Price (INR)',
       'actual_price', 'discount_percentage', 'rating', 'Rating Count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'IMG_LINK', 'product_link'],
      dtype='object')

### Investigating the Malformed Price

During the initial price check, one non-missing value (3657.66.00) could not be converted into a numeric value. Rather than replacing it immediately, I checked the other information in the same record to see whether the correct price could be reasonably determined.

In [51]:
amazon_data_copy.loc[
    227,
    ["product_name", "Discounted_Price (INR)", "actual_price", "discount_percentage"]
]

product_name              Butterfly Smart Wet Grinder, 2L (White) with C...
Discounted_Price (INR)                                           3657.66.00
actual_price                                                         ₹5,156
discount_percentage                                                     29%
Name: 227, dtype: object

### Handling the Malformed Discounted Price

One non-missing value in "Discounted_Price (INR)" could not be converted into a number because it was recorded as "3657.66.00".

I checked the other fields in the same row before deciding how to treat it. The actual price is ₹5,156 and the recorded discount is 29%. Removing the extra ".00" gives a discounted price of ₹3,657.66, which implies a discount of approximately 29.06%. This is consistent with the recorded 29% discount after rounding.

I therefore treated "3657.66.00" as a formatting error and corrected it to "3657.66" rather than replacing the value with a statistical estimate.

In [52]:
# Correct the extra decimal portion in the one malformed price value
amazon_data_copy.loc[227, "Discounted_Price (INR)"] = "3657.66"

In [53]:
amazon_data_copy.loc[
    227,
    ["Discounted_Price (INR)", "actual_price", "discount_percentage"]
]

Discounted_Price (INR)    3657.66
actual_price               ₹5,156
discount_percentage           29%
Name: 227, dtype: object

### Standardising "Discounted_Price (INR)"

The discounted-price column contains currency symbols, commas, and text formatting that prevent pandas from treating the values as numerical data.

I removed the formatting characters and converted the column to a numeric type. This makes the field suitable for range checks, calculations, and later analysis.

In [54]:
# Remove currency formatting and store discounted prices as numbers
amazon_data_copy["Discounted_Price (INR)"] = pd.to_numeric(
    amazon_data_copy["Discounted_Price (INR)"]
    .astype("string")
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip(),
    errors="coerce"
)

In [55]:
invalid_discounted_price = amazon_data_copy[
    amazon_data_copy["Discounted_Price (INR)"] <= 0
]

invalid_discounted_price[
    [
        "product_name",
        "Discounted_Price (INR)",
        "actual_price",
        "discount_percentage"
    ]
]

,product_name,Discounted_Price (INR),actual_price,discount_percentage
13,Havells D'zire 1000 watt Dry Iron With America...,0.0,"₹1,295",31%
183,Boult Audio Airbass Propods X TWS Bluetooth Tr...,0.0,"₹5,999",82%
365,7SEVEN® Compatible for Samsung Smart 4K Ultra ...,-399.0,₹999,60%
539,Pigeon Kessel Multipurpose Kettle (12173) 1.2 ...,-1499.0,"₹1,775",16%
947,Wayona USB Type C 65W Fast Charging 2M/6Ft Lon...,-325.0,₹999,67%
1020,Pigeon by Stovekraft Amaze Plus Electric Kettl...,0.0,"₹1,345",48%
1079,"Redmi 9A Sport (Carbon Black, 2GB RAM, 32GB St...",0.0,"₹7,999",19%
1088,HP 682 Black Original Ink Cartridge,-828.0,₹861,4%
1133,HealthSense Rechargeable Lint Remover for Clot...,-999.0,"₹1,500",33
1213,House of Quirk Reusable Sticky Picker Cleaner ...,-299.0,₹499,40%
1237,Fire-Boltt Phoenix Smart Watch with Bluetooth ...,0.0,9999,80%
1313,Rico IRPRO 1500 Watt Japanese Technology Elect...,-999.0,"₹1,075",7%
1325,ECOVACS DEEBOT N8 2-in-1 Robotic Vacuum Cleane...,-27900.0,"₹59,900",53%

### Handling Invalid Discounted Prices

The discounted-price column contains 13 values that are either zero or negative. These values cannot represent valid product selling prices.

Rather than removing the affected product records, I checked the corresponding actual price and discount percentage. Since the discounted price can be derived from these two fields, I used the recorded actual price and discount to calculate a replacement value for the invalid entries.

This approach keeps the product records in the dataset while correcting the specific field that contains the data-quality problem.

In [56]:
# Calculate what the discounted price should be based on the actual price and discount
expected_discounted_price = actual_price_check * (1 - discount_check / 100)

In [57]:
expected_discounted_price.loc[invalid_discounted_price.index]

13       893.55
183     1079.82
365       399.6
539      1491.0
947      329.67
1020      699.4
1079    6479.19
1088     826.56
1133     1005.0
1213      299.4
1237     1999.8
1313     999.75
1325    28153.0
dtype: Float64

In [58]:
# Replace zero and negative discounted prices with values calculated from the recorded price and discount
amazon_data_copy.loc[
    invalid_discounted_price.index,
    "Discounted_Price (INR)"
] = expected_discounted_price.loc[invalid_discounted_price.index]

In [59]:
(amazon_data_copy["Discounted_Price (INR)"] <= 0).sum()

np.int64(0)

In [60]:
amazon_data_copy.loc[
    invalid_discounted_price.index,
    ["product_name", "Discounted_Price (INR)", "actual_price", "discount_percentage"]
]

,product_name,Discounted_Price (INR),actual_price,discount_percentage
13,Havells D'zire 1000 watt Dry Iron With America...,893.55,"₹1,295",31%
183,Boult Audio Airbass Propods X TWS Bluetooth Tr...,1079.82,"₹5,999",82%
365,7SEVEN® Compatible for Samsung Smart 4K Ultra ...,399.6,₹999,60%
539,Pigeon Kessel Multipurpose Kettle (12173) 1.2 ...,1491.0,"₹1,775",16%
947,Wayona USB Type C 65W Fast Charging 2M/6Ft Lon...,329.67,₹999,67%
1020,Pigeon by Stovekraft Amaze Plus Electric Kettl...,699.4,"₹1,345",48%
1079,"Redmi 9A Sport (Carbon Black, 2GB RAM, 32GB St...",6479.19,"₹7,999",19%
1088,HP 682 Black Original Ink Cartridge,826.56,₹861,4%
1133,HealthSense Rechargeable Lint Remover for Clot...,1005.0,"₹1,500",33
1213,House of Quirk Reusable Sticky Picker Cleaner ...,299.4,₹499,40%
1237,Fire-Boltt Phoenix Smart Watch with Bluetooth ...,1999.8,9999,80%
1313,Rico IRPRO 1500 Watt Japanese Technology Elect...,999.75,"₹1,075",7%
1325,ECOVACS DEEBOT N8 2-in-1 Robotic Vacuum Cleane...,28153.0,"₹59,900",53%

### Discounted Price Cleaning

The discounted-price column initially contained currency formatting, one malformed value, and 13 zero or negative prices.

The malformed value "3657.66.00" was corrected to "3657.66" after checking the actual price and discount recorded for the same product. The zero and negative prices were then replaced with values calculated from the actual price and applicable discount.

A final check returned 0 zero or negative values, confirming that the invalid discounted prices identified during the quality assessment had been addressed.

### Checking the Actual Price Values

The "actual_price" column is currently stored as text because it contains currency symbols and comma formatting. I first converted a temporary version of the column to numeric form so that invalid values could be identified.

Before applying the cleaned values to the working dataset, I checked whether any non-missing entries failed to convert. This prevents a formatting problem from being silently treated as an ordinary missing value.

In [61]:
# Find actual prices that were present but could not be converted to numbers
unparsed_actual_price = amazon_data.loc[
    amazon_data["actual_price"].notna() &
    actual_price_check.isna(),
    "actual_price"
]

unparsed_actual_price

Series([], Name: actual_price, dtype: object)

In [62]:
# Replace the text-formatted actual prices with their numeric versions
amazon_data_copy["actual_price"] = actual_price_check

In [63]:
amazon_data_copy["actual_price"].dtype

Float64Dtype()

In [64]:
invalid_actual_price = amazon_data_copy[
    amazon_data_copy["actual_price"] <= 0
]

invalid_actual_price[
    [
        "product_name",
        "actual_price",
        "Discounted_Price (INR)",
        "discount_percentage"
    ]
]

,product_name,actual_price,Discounted_Price (INR),discount_percentage
100,"Skadioo WiFi Adapter for pc | Car Accessories,...",-499.0,199.0,60%
331,MI Braided USB Type-C Cable for Charging Adapt...,0.0,349.0,13%
583,"Brand Conquer 6 in 1 with OTG, SD Card Reader,...",0.0,549.0,45
753,AmazonBasics High-Speed Braided HDMI Cable - 3...,0.0,269.0,59%
787,Tosaa T2STSR Sandwich Gas Toaster Regular (Black),-350.0,260.0,26%
893,"OPPO A74 5G (Fantastic Purple,6GB RAM,128GB St...",-20990.0,15490.0,26%
1046,Wayona Nylon Braided (2 Pack) Lightning Fast U...,-1999.0,649.0,68%
1187,"INALSA Hand Blender 1000 Watt with Chopper, Wh...",0.0,2742.0,31%
1231,Samsung 80 cm (32 inches) Wondertainment Serie...,0.0,15490.0,26%
1309,Crompton Insta Delight Fan Circulator Room Hea...,-4200.0,2590.0,38%
1335,"Ambrane 27000mAh Power Bank, 20W Fast Charging...",-2999.0,2499.0,17%
1361,Usha Janome Dream Stitch Automatic Zig-Zag Ele...,-12150.0,9799.0,19%
1448,SanDisk Ultra 128 GB USB 3.0 Pen Drive (Black),-2500.0,889.0,64%

In [65]:
# Work backwards from the discounted price to estimate the actual price
expected_actual_price = (
    amazon_data_copy["Discounted_Price (INR)"] /
    (1 - discount_check / 100)
)

In [66]:
expected_actual_price.loc[invalid_actual_price.index]

100            497.5
331       401.149425
583       998.181818
753       656.097561
787       351.351351
893     20932.432432
1046        2028.125
1187     3973.913043
1231    20932.432432
1309     4177.419355
1335     3010.843373
1361    12097.530864
1448     2469.444444
dtype: Float64

### Handling Invalid Actual Prices

The "actual_price" column contained 13 zero or negative values, which are not valid product prices. After converting the column to numeric form, I compared these records with their discounted prices and recorded discount percentages.

Since all 13 affected records had usable discount percentages, I calculated the expected actual price by working backwards from the discounted price. This allowed the affected product records to be retained instead of deleting the entire rows.

The calculated values may contain decimals because the discount percentages are recorded as rounded percentages, so the recovered prices are kept to two decimal places.

In [67]:
# Keep the recovered prices to two decimal places
expected_actual_price = expected_actual_price.round(2)

In [68]:
# Replace the zero and negative prices with the calculated values
amazon_data_copy.loc[
    invalid_actual_price.index,
    "actual_price"
] = expected_actual_price.loc[invalid_actual_price.index]

In [69]:
(amazon_data_copy["actual_price"] <= 0).sum()

np.int64(0)

In [70]:
amazon_data_copy.loc[
    invalid_actual_price.index,
    ["product_name", "actual_price", "Discounted_Price (INR)", "discount_percentage"]
]

,product_name,actual_price,Discounted_Price (INR),discount_percentage
100,"Skadioo WiFi Adapter for pc | Car Accessories,...",497.5,199.0,60%
331,MI Braided USB Type-C Cable for Charging Adapt...,401.15,349.0,13%
583,"Brand Conquer 6 in 1 with OTG, SD Card Reader,...",998.18,549.0,45
753,AmazonBasics High-Speed Braided HDMI Cable - 3...,656.1,269.0,59%
787,Tosaa T2STSR Sandwich Gas Toaster Regular (Black),351.35,260.0,26%
893,"OPPO A74 5G (Fantastic Purple,6GB RAM,128GB St...",20932.43,15490.0,26%
1046,Wayona Nylon Braided (2 Pack) Lightning Fast U...,2028.13,649.0,68%
1187,"INALSA Hand Blender 1000 Watt with Chopper, Wh...",3973.91,2742.0,31%
1231,Samsung 80 cm (32 inches) Wondertainment Serie...,20932.43,15490.0,26%
1309,Crompton Insta Delight Fan Circulator Room Hea...,4177.42,2590.0,38%
1335,"Ambrane 27000mAh Power Bank, 20W Fast Charging...",3010.84,2499.0,17%
1361,Usha Janome Dream Stitch Automatic Zig-Zag Ele...,12097.53,9799.0,19%
1448,SanDisk Ultra 128 GB USB 3.0 Pen Drive (Black),2469.44,889.0,64%

The 13 invalid actual-price values were replaced using the corresponding discounted price and valid discount percentage. After the correction, the range check returned 0 zero or negative actual prices, confirming that the invalid values identified during the initial assessment had been addressed.

In [71]:
# Store the cleaned discount values as numbers
amazon_data_copy["discount_percentage"] = discount_check

In [72]:
amazon_data_copy["discount_percentage"].dtype

Int64Dtype()

In [73]:
invalid_discount = amazon_data_copy[
    (amazon_data_copy["discount_percentage"] < 0) |
    (amazon_data_copy["discount_percentage"] > 100)
]

invalid_discount[
    [
        "product_name",
        "actual_price",
        "Discounted_Price (INR)",
        "discount_percentage"
    ]
]

,product_name,actual_price,Discounted_Price (INR),discount_percentage
476,"iQOO Z6 Lite 5G by vivo (Mystic Night, 6GB RAM...",18999.0,15499.0,120
647,Sounce Fast Phone Charging Cable & Data Sync U...,1899.0,199.0,120
766,Noise ColorFit Pulse Smartwatch with 3.56 cm (...,4999.0,1599.0,120
779,SanDisk Ultra Dual Drive Go USB Type C Pendriv...,2800.0,1109.0,120
807,"FIGMENT Handheld Milk Frother Rechargeable, 3-...",1599.0,699.0,120
996,Portronics Konnect CL 20W POR-1067 Type-C to 8...,899.0,350.0,150
1227,"Lenovo 400 Wireless Mouse, 1200DPI Optical Sen...",1390.0,629.0,150
1380,KINGONE Wireless Charging Pencil (2nd Generati...,6999.0,2599.0,-15

In [74]:
# Work out the discount percentage from the two cleaned price fields
expected_discount = (
    (amazon_data_copy["actual_price"] - amazon_data_copy["Discounted_Price (INR)"])
    / amazon_data_copy["actual_price"]
    * 100
).round(2)

expected_discount.loc[invalid_discount.index]

476     18.42
647     89.52
766     68.01
779     60.39
807     56.29
996     61.07
1227    54.75
1380    62.87
dtype: Float64

### Handling Invalid Discount Percentages

The `discount_percentage` column contained 8 values outside the valid 0–100% range. Instead of replacing these values with a general statistic such as the mode, I used the cleaned `actual_price` and `Discounted_Price (INR)` values to calculate the discount for each affected product.

The calculated percentages were all within the valid range, so they provide a reasonable basis for correcting the invalid entries. The values were rounded to two decimal places because the calculation is based on the recorded prices.

In [75]:
# Convert the column to Float64 so it can hold decimal percentages, then replace the invalid values
amazon_data_copy["discount_percentage"] = amazon_data_copy["discount_percentage"].astype("Float64")
amazon_data_copy.loc[
    invalid_discount.index,
    "discount_percentage"
] = expected_discount.loc[invalid_discount.index]

In [76]:
(
    (amazon_data_copy["discount_percentage"] < 0) |
    (amazon_data_copy["discount_percentage"] > 100)
).sum()

np.int64(0)

In [77]:
amazon_data_copy["discount_percentage"].dtype

Float64Dtype()

The corrected discount values include decimal percentages, so the column was changed from an integer-compatible type to a floating-point type before the replacement values were applied. This allows the cleaned column to retain the calculated percentages without losing their decimal values.

### Standardising the Rating Column

The "rating" column contains both valid numerical ratings and non-standard entries. During the initial inspection, values such as "New" and "|" were found alongside numerical values outside the expected 1–5 range.

I will first convert the column to numeric form so that the non-numeric entries can be identified as missing values. I will then check the numerical range and handle any invalid ratings separately rather than assigning arbitrary values to them.

In [78]:
# Convert the rating values to numbers and turn text placeholders into missing values
amazon_data_copy["rating"] = pd.to_numeric(
    amazon_data_copy["rating"],
    errors="coerce"
)

In [79]:
amazon_data_copy["rating"].dtype

dtype('float64')

In [80]:
invalid_rating = amazon_data_copy[
    (amazon_data_copy["rating"] < 1) |
    (amazon_data_copy["rating"] > 5)
]

invalid_rating[
    ["product_name", "rating"]
]

                                           product_name  rating
166   Lifelong LLQH922 Regalia 800 W (ISI Certified)...     6.0
472   LG 108 cm (43 inches) 4K Ultra HD Smart LED TV...    -1.0
575   Oratech Coffee Frother electric, milk frother ...     5.5
691   Cuzor 12V Mini ups for WiFi Router | Power Bac...     6.0
717   LIRAMARK Webcam Cover Slide, Ultra Thin Laptop...     6.0
832   ZIGMA WinoteK WinoteK Sun Instant Water Geyser...    -1.0
862   SWAPKART Fast Charging Cable and Data Sync USB...     5.5
946   PIDILITE FEVICRYL ACRYLIC COLOURS SUNFLOWER KI...    -1.0
1087  Lifelong LLQH925 Dyno Quartz Heater 2 Power se...     6.0
1177  VW 60 cm (24 inches) Premium Series HD Ready L...    -1.0
1238  INALSA Vaccum Cleaner Handheld 800W High Power...     5.5
1265  Shakti Technology S3 High Pressure Car Washer ...     6.0

In [81]:
amazon_data_copy["rating"].dtype

dtype('float64')

### Handling Invalid Ratings

The rating column contains 12 numerical values outside the expected 1–5 range. Because there is no reliable way to determine the original rating from the other product fields, I did not try to replace these values with guessed ratings.

Instead, the invalid ratings were converted to missing values. They will be considered together with the ratings that were already missing or could not be converted, and an appropriate missing-data treatment will be applied later.

In [82]:
# Mark ratings outside the valid 1–5 range as missing
amazon_data_copy.loc[invalid_rating.index, "rating"] = np.nan

In [83]:
( (amazon_data_copy["rating"] < 1) |
    (amazon_data_copy["rating"] > 5)
).sum()

np.int64(0)

In [84]:
amazon_data_copy["rating"].isna().sum()

np.int64(32)

The invalid numerical ratings were converted to missing values, and the final range check returned 0 values outside the valid 1–5 range.

The missing-rating count will now include both the original missing values, the non-numeric placeholders, and the invalid numerical ratings. These missing values will be handled together during the missing-data treatment stage rather than assigning arbitrary ratings.

### Standardising "Rating Count"

The "Rating Count" column contains several different representations of review counts. Some values use commas, some use the "K" abbreviation, and some contain text such as "Not enough ratings".

Before converting the column to a numeric type, these formats need to be standardised so that the resulting values represent the actual number of ratings as consistently as possible. Text placeholders that do not provide a usable count will be treated as missing.

In [85]:
amazon_data_copy.loc[
    amazon_data_copy["Rating Count"].astype("string").str.contains("K", na=False),
    "Rating Count"
].head()

77      4.4K
94     17.4K
120     0.2K
155     2.9K
229     4.4K
Name: Rating Count, dtype: object

In [86]:
# Start by treating the rating counts as text so the different formats can be cleaned
rating_count_check = (
    amazon_data_copy["Rating Count"]
    .astype("string")
    .str.strip()
    .str.replace(",", "", regex=False)
)

In [87]:
def convert_rating_count(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if value.lower().endswith("k"):
        return float(value[:-1]) * 1000

    if value.replace(".", "", 1).isdigit():
        return float(value)

    return np.nan

In [88]:
rating_count_check = rating_count_check.apply(convert_rating_count)

In [89]:
rating_count_check.head(10)

0     2908.0
1     2664.0
2     1811.0
3    12375.0
4     1771.0
5      714.0
6    18998.0
7      163.0
8     7807.0
9      197.0
Name: Rating Count, dtype: float64

In [90]:
rating_count_check.loc[[77, 94, 120, 155, 229]]

77      4400.0
94     17400.0
120      200.0
155     2900.0
229     4400.0
Name: Rating Count, dtype: float64

In [91]:
rating_count_check.isna().sum()

np.int64(27)

In [92]:
# Replace the mixed text formats with the cleaned numeric rating counts
amazon_data_copy["Rating Count"] = rating_count_check

In [93]:
amazon_data_copy["Rating Count"].dtype

dtype('float64')

### Rating Count Cleaning

The "Rating Count" column contained comma-formatted numbers, values written using the "K" abbreviation, and the text placeholder "Not enough ratings".

The different numeric formats were converted into a common numeric representation. For example, values such as "4.4K" were converted to 4,400. Entries that did not provide an actual rating count, including the "Not enough ratings" placeholder, were treated as missing rather than assigning an unsupported value.

The cleaned values were then stored back in the working dataset as a numeric column.

### Standardising Product Links

The initial quality check found 29 non-missing product links without the "https://" scheme. The affected values still begin with "www.amazon.in", so the links can be repaired without changing the actual destination.

I will add "https://" only to links that are missing it and leave already valid links unchanged.

In [94]:
# Select links that exist but are missing the https:// prefix
product_mask = (
    amazon_data_copy["product_link"].notna() &
    ~amazon_data_copy["product_link"].str.startswith("https://", na=False)
)

In [95]:
amazon_data_copy.loc[product_mask, "product_link"] = (
    "https://" + amazon_data_copy.loc[product_mask, "product_link"]
)

In [96]:
amazon_data_copy["product_link"].dropna().str.startswith("https://", na=False).value_counts()

product_link
True    1470
Name: count, dtype: int64

### Standardising Image Links

The same issue was found in the image-link column: 29 non-missing values were missing the "https://" scheme. Since these values still contain the valid Amazon image domain, I used the same approach to restore the missing scheme without changing links that were already correctly formatted.

In [97]:
# Select image links that exist but are missing the https:// prefix
image_mask = (
    amazon_data_copy["IMG_LINK"].notna() &
    ~amazon_data_copy["IMG_LINK"].str.startswith("https://", na=False)
)

In [98]:
amazon_data_copy.loc[image_mask, "IMG_LINK"] = (
    "https://" + amazon_data_copy.loc[image_mask, "IMG_LINK"])

In [99]:
amazon_data_copy["IMG_LINK"].dropna().str.startswith("https://",na=False).value_counts()

IMG_LINK
True    1470
Name: count, dtype: int64

## Missing Data Handling

After standardising the main fields, I reassessed the missing values because some invalid or non-standard entries were converted to missing values during the cleaning process.

I will now review the remaining missing values by column and choose a suitable treatment based on what the field represents. I will avoid using the same imputation method for every column, since replacing a missing product identifier, price, rating, or review text with the same type of value would not make sense.

In [100]:
missing_report_after = pd.DataFrame({
    "Null Count": amazon_data_copy.isna().sum(),
    "Null Percentage": (
        amazon_data_copy.isna().sum() / len(amazon_data_copy) * 100
    ).round(2)
})

missing_report_after

                        Null Count  Null Percentage
product_id                       8             0.54
product_name                    11             0.74
category                        14             0.95
Discounted_Price (INR)          14             0.95
actual_price                    14             0.95
discount_percentage             14             0.95
rating                          32             2.16
Rating Count                    27             1.82
about_product                   14             0.95
user_id                          0             0.00
user_name                        1             0.07
review_id                        0             0.00
review_title                     6             0.41
review_content                   4             0.27
IMG_LINK                        11             0.74
product_link                    11             0.74

In [101]:
len(amazon_data_copy)

1481

In [102]:
# Check for duplicate rows
amazon_data_copy.duplicated().sum()

np.int64(2)

### Reviewing Missing-Value Patterns

The updated missing-value report shows that the amount of missing data is relatively small in each column, but the missing values may occur in the same records.

Before choosing an imputation or deletion method, I will check how the missing values overlap across rows. This will help me avoid deleting records unnecessarily and will give me a better basis for deciding which fields can be imputed and which ones should not be invented.

In [103]:
# Check how many fields are missing in each row
missing_per_row = amazon_data_copy.isna().sum(axis=1)
missing_per_row.value_counts().sort_index()

0    1314
1     154
2      12
3       1
Name: count, dtype: int64

In [104]:
product_fields = [
    "product_id",
    "product_name",
    "category",
    "Discounted_Price (INR)",
    "actual_price",
    "discount_percentage",
    "about_product"]

amazon_data_copy.loc[
    amazon_data_copy[product_fields].isna().any(axis=1),
    product_fields]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,about_product
3,B01MQ2A86A,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",Computers&Accessories|Accessories&Peripherals|...,<NA>,1645.0,21.0,Quieter Click: Logitech’s SilentTouch Technolo...
4,B08GM5S4CQ,Havells Instanio 10 Litre Storage Water Heater...,NaN,6990.0,14290.0,51.0,Suitable for high-rise buildings and pressure ...
7,B08G43CCLC,NK STAR 950 Mbps USB WiFi Adapter Wireless Net...,Computers&Accessories|NetworkingDevices|Networ...,218.0,999.0,<NA>,[NOTE - >>Not Support to DVR and HDTV]..[CONNE...
26,B076VQS87V,NaN,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",457.0,799.0,43.0,"Golden American Heritage Soleplate,Overheat Sa..."
30,B09C635BMM,Cotbolt Silicone Case Cover Compatible for Sam...,"Electronics|HomeTheater,TV&Video|Accessories|R...",349.0,999.0,65.0,NaN
...,...,...,...,...,...,...,...
1365,B09MKG4ZCM,Xiaomi Mi 4A Dual_Band Ethernet 1200Mbps Speed...,Computers&Accessories|NetworkingDevices|Routers,1565.0,2999.0,<NA>,Speed - Dual Band Gigabit Wifi Router : Upto 1...
1423,B07W7Z6DVL,"Infinity (JBL Fuze 100, Wireless Portable Blue...",Electronics|HomeAudio|Speakers|OutdoorSpeakers,1499.0,2999.0,<NA>,Compact Portable Bluetooth Speakers. Wireless ...
1426,B09VKWGZD7,"AGARO Supreme High Pressure Washer, 1800 Watts...","Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",4789.0,8990.0,47.0,NaN
1464,B07924P3C5,Storite High Speed Micro USB 3.0 Cable A to Mi...,NaN,299.0,799.0,63.0,High performance Micro USB 3.0 cable connects ...
1485,B07DZ986Q2,Philips EasyTouch Plus Standing Garment Steame...,NaN,7799.0,8995.0,13.0,Philips EasyTouch Plus 523/60 Standing Garment...

In [105]:
amazon_data_copy.loc[
    amazon_data_copy["product_id"].isna() |
    amazon_data_copy["product_name"].isna(),
    [
        "product_id",
        "product_name",
        "category",
        "Discounted_Price (INR)",
        "actual_price",
        "discount_percentage"
    ]
]

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage
26,B076VQS87V,NaN,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",457.0,799.0,43.0
104,B07222HQKP,NaN,Computers&Accessories|ExternalDevices&DataStor...,657.0,999.0,34.0
173,B09MM6P76N,NaN,"Electronics|HomeTheater,TV&Video|Accessories|R...",349.0,599.0,42.0
203,NaN,"AGARO Ace 1600 Watts, 21.5 kPa Suction Power, ...","Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",6236.0,9999.0,38.0
255,NaN,"iQOO vivo Z6 5G (Chromatic Blue, 6GB RAM, 128G...",Electronics|Mobiles&Accessories|Smartphones&Ba...,16499.0,20999.0,21.0
263,NaN,Eco Crystal J 5 inch Cartridge (Pack of 2),Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,199.0,400.0,50.0
322,B08HF4W2CT,NaN,Electronics|Mobiles&Accessories|MobileAccessor...,1599.0,3499.0,54.0
429,NaN,"iQOO 9 SE 5G (Sunset Sierra, 8GB RAM, 128GB St...",Electronics|Mobiles&Accessories|Smartphones&Ba...,29990.0,39990.0,25.0
451,NaN,FLiX (Beetel) USB to Type C PVC Data Sync & 2A...,Computers&Accessories|Accessories&Peripherals|...,139.0,249.0,44.0
571,B0B9BD2YL4,NaN,Electronics|Mobiles&Accessories|MobileAccessor...,2599.0,6999.0,63.0
602,NaN,TP-Link Nano AC600 USB Wi-Fi Adapter(Archer T2...,Computers&Accessories|NetworkingDevices|Networ...,999.0,1599.0,38.0
657,B07MKMFKPG,NaN,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,6999.0,10590.0,34.0
658,NaN,Simxen Egg Boiler Electric Automatic Off 7 Egg...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,349.0,999.0,65.0
715,B0BBVKRP7B,NaN,Electronics|WearableTechnology|SmartWatches,281.0,1999.0,86.0
741,B07WHQWXL7,NaN,Electronics|Mobiles&Accessories|Smartphones&Ba...,15499.0,20999.0,26.0
873,B00NH13Q8W,NaN,Computers&Accessories|Accessories&Peripherals|...,299.0,800.0,63.0
1103,B09NS5TKPN,NaN,"Home&Kitchen|Heating,Cooling&AirQuality|AirCon...",42990.0,75990.0,43.0
1306,NaN,"iBELL SEK170BM Premium Electric Kettle, 1.7 Li...",Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,809.0,1950.0,59.0
1355,B08HDJ86NZ,NaN,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53.0

### Handling Missing Product Identifiers

The "product_id" and "product_name" fields are used to identify the product represented by each record. There are 8 rows with a missing "product_id" and 11 rows with a missing "product_name".

I did not use mode imputation for these fields because assigning an existing product ID or product name to a different record would create false product information. Since these fields are central to identifying the product and the missing values cannot be reliably inferred from the available data, the affected records will be removed.

This affects 19 rows in total, which is a small proportion of the dataset, while avoiding the introduction of fabricated product information.

In [106]:
# Identify records that are missing either the product ID or product name
identity_mask = (
    amazon_data_copy["product_id"].isna() |
    amazon_data_copy["product_name"].isna()
)

In [107]:
identity_rows_removed = identity_mask.sum()
identity_rows_removed

np.int64(19)

In [108]:
amazon_data_copy = amazon_data_copy.loc[~identity_mask]

In [109]:
amazon_data_copy[["product_id", "product_name"]].isna().sum()

product_id      0
product_name    0
dtype: int64

In [110]:
len(amazon_data_copy)

1462

The 19 records with a missing "product_id" or "product_name" were removed. After the removal, both product-identification fields contain 0 missing values.

The remaining dataset contains 1,462 rows, so the deletion affected only a small portion of the cleaned dataset.

In [111]:
# Recheck the missing values after removing the incomplete product records
current_missing = pd.DataFrame({
    "Null Count": amazon_data_copy.isna().sum(),
    "Null Percentage": (
        amazon_data_copy.isna().sum() / len(amazon_data_copy) * 100
    ).round(2)
})

current_missing[current_missing["Null Count"] > 0]

                        Null Count  Null Percentage
category                        14             0.96
Discounted_Price (INR)          14             0.96
actual_price                    14             0.96
discount_percentage             14             0.96
rating                          32             2.19
Rating Count                    27             1.85
about_product                   14             0.96
user_name                        1             0.07
review_title                     6             0.41
review_content                   4             0.27
IMG_LINK                        11             0.75
product_link                    11             0.75

### Checking the Missing Product Information

The updated report shows the same number of missing values in the category, price, discount, and product-description fields. Before deciding how to handle them, I checked whether these gaps occur in the same records. This helps me avoid filling several missing fields independently when a product record may be missing most of its main information.

In [112]:
# Check how many of the main product fields are missing in each row
core_product_fields = [
    "category",
    "Discounted_Price (INR)",
    "actual_price",
    "discount_percentage",
    "about_product"]

missing_core_fields = amazon_data_copy[core_product_fields].isna().sum(axis=1)
missing_core_fields.value_counts().sort_index()

0    1398
1      58
2       6
Name: count, dtype: int64

### Checking Which Product Fields Are Missing Together

The previous check showed that most rows have complete product information, while a smaller number have one or two missing fields. I checked the specific combinations of missing fields so that I can decide whether any missing values can be recovered from related information before using imputation.

In [113]:
# Group the affected rows by the product fields that are missing
missing_core_patterns = (
    amazon_data_copy[core_product_fields]
    .isna()
    .apply(lambda row: ", ".join(row.index[row]), axis=1)
)

missing_core_patterns[missing_core_patterns != ""].value_counts()

Discounted_Price (INR)                  13
discount_percentage                     12
about_product                           12
category                                11
actual_price                            10
category, actual_price                   3
discount_percentage, about_product       2
Discounted_Price (INR), actual_price     1
Name: count, dtype: int64

### Recovering Missing Discount Percentages

The missing-value check showed that some products have an actual price and discounted price but no recorded discount percentage. Since the two prices are available, I can calculate the missing discount instead of using a general replacement value.

This keeps the discount consistent with the prices recorded for the product.

In [114]:
# Calculate missing discounts from the actual and discounted prices
missing_discount_mask = amazon_data_copy["discount_percentage"].isna()

calculated_discount = (
    (amazon_data_copy["actual_price"] - amazon_data_copy["Discounted_Price (INR)"])
    / amazon_data_copy["actual_price"]
    * 100
).round(2)

discounts_filled = missing_discount_mask.sum()

amazon_data_copy.loc[missing_discount_mask, "discount_percentage"] = (
    calculated_discount.loc[missing_discount_mask]
)

discounts_filled

np.int64(14)

### Recovering Missing Discounted Prices

For records where the discounted price is missing but the actual price and discount are available, I can calculate the selling price using those two fields. This is preferable to filling the gaps with the median because the replacement can be linked directly to the product's recorded pricing information.

In [115]:
# Find missing discounted prices that can be calculated from the other two fields
missing_discounted_mask = amazon_data_copy["Discounted_Price (INR)"].isna()

can_calculate_discounted = (
    missing_discounted_mask
    & amazon_data_copy["actual_price"].notna()
    & amazon_data_copy["discount_percentage"].notna()
)

calculated_discounted_price = (
    amazon_data_copy["actual_price"]
    * (1 - amazon_data_copy["discount_percentage"] / 100)
).round(2)

discounted_prices_filled = can_calculate_discounted.sum()

amazon_data_copy.loc[can_calculate_discounted, "Discounted_Price (INR)"] = (
    calculated_discounted_price.loc[can_calculate_discounted]
)

discounted_prices_filled

np.int64(13)

### Recovering Missing Actual Prices

Some records have a discounted price and discount percentage but no actual price. Where those two values are available and the discount is below 100%, I can calculate the actual price by reversing the discount formula.

I will only apply this calculation where the required values are present and the calculation is mathematically valid.

In [116]:
# Find missing actual prices that can be recovered from the discounted price and discount
missing_actual_mask = amazon_data_copy["actual_price"].isna()

can_calculate_actual = (
    missing_actual_mask
    & amazon_data_copy["Discounted_Price (INR)"].notna()
    & amazon_data_copy["discount_percentage"].notna()
    & amazon_data_copy["discount_percentage"].lt(100).fillna(False)
)

calculated_actual_price = (
    amazon_data_copy["Discounted_Price (INR)"]
    / (1 - amazon_data_copy["discount_percentage"] / 100)
).round(2)

actual_prices_filled = can_calculate_actual.sum()

amazon_data_copy.loc[can_calculate_actual, "actual_price"] = (
    calculated_actual_price.loc[can_calculate_actual]
)

actual_prices_filled

np.int64(13)

In [117]:
price_missing_check = amazon_data_copy[
    ["Discounted_Price (INR)", "actual_price", "discount_percentage"]
].isna().sum()

price_missing_check

Discounted_Price (INR)    1
actual_price              1
discount_percentage       0
dtype: int64

In [118]:
print("Discount percentages filled:", discounts_filled)
print("Discounted prices recovered:", discounted_prices_filled)
print("Actual prices recovered:", actual_prices_filled)

Discount percentages filled: 14
Discounted prices recovered: 13
Actual prices recovered: 13

### Reviewing the Remaining Missing Prices

After recovering prices from the available pricing information, one record still has both "actual_price" and "Discounted_Price (INR)" missing. I am checking the remaining product details before deciding how to handle it, rather than filling both values independently without considering their relationship.

In [119]:
# Check the product details for the record with the remaining missing prices
unresolved_prices = amazon_data_copy.loc[
    amazon_data_copy["Discounted_Price (INR)"].isna() |
    amazon_data_copy["actual_price"].isna(),
    [
        "product_id",
        "product_name",
        "category",
        "Discounted_Price (INR)",
        "actual_price",
        "discount_percentage"
    ]
]

unresolved_prices

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage
1130,B086Q3QMFS,"Classmate Drawing Book - Unruled, 40 Pages, 21...",OfficeProducts|OfficePaperProducts|Paper|Stati...,<NA>,<NA>,0.0

### Handling the Remaining Missing Prices

One product record still has both its actual and discounted prices missing. Its recorded discount is 0%, so the two prices should be equal, but the original amount cannot be recovered directly.

Before imputing the missing values, I will check the typical actual price of other products in the same category. This provides a more relevant estimate than using the median price of all products in the dataset.

In [120]:
# Find the available actual prices for products in the same category
unresolved_category = amazon_data_copy.loc[1130, "category"]

category_actual_prices = amazon_data_copy.loc[
    (amazon_data_copy["category"] == unresolved_category)
    & amazon_data_copy["actual_price"].notna(),
    "actual_price"
]

category_actual_prices.count(), category_actual_prices.median()

(np.int64(7), np.float64(180.0))

### Handling the Last Missing Prices

One product record still had both its actual and discounted prices missing. I checked the prices of other products in the same category and found seven usable records, with a median actual price of 180.

I used this median as an estimate for the missing actual price. Since the recorded discount is 0%, I assigned the same amount to the discounted price. This keeps the pricing fields consistent, although the replacement remains an estimate rather than a verified price for that particular product.

In [121]:
# Use the category median to fill the two missing prices in row 1130
category_median_price = category_actual_prices.median()

amazon_data_copy.loc[
    1130,
    ["actual_price", "Discounted_Price (INR)"]
] = category_median_price

In [122]:
amazon_data_copy.loc[
    1130,
    ["product_name", "actual_price", "Discounted_Price (INR)", "discount_percentage"]
]

product_name              Classmate Drawing Book - Unruled, 40 Pages, 21...
actual_price                                                          180.0
Discounted_Price (INR)                                                180.0
discount_percentage                                                     0.0
Name: 1130, dtype: object

In [123]:
amazon_data_copy[
    ["actual_price", "Discounted_Price (INR)"]
].isna().sum()

actual_price              0
Discounted_Price (INR)    0
dtype: int64

Handling Missing Categories

The "category" column contains detailed product-category paths, so using the most common category to fill every missing value could incorrectly classify products. Since only 14 records have a missing category, I chose to remove those records rather than assign them a category that cannot be confirmed from the available data.

This removes a small proportion of the dataset while keeping the remaining category labels reliable.

In [124]:
# Count the records with no category before removing them
category_rows_removed = amazon_data_copy["category"].isna().sum()

# Remove records whose category cannot be confirmed
amazon_data_copy = amazon_data_copy.loc[
    amazon_data_copy["category"].notna()
].copy()

category_rows_removed

np.int64(14)

In [125]:
amazon_data_copy["category"].isna().sum()

np.int64(0)

In [126]:
len(amazon_data_copy)

1448

### Handling Missing Ratings

After correcting the invalid ratings and converting the non-numeric placeholders to missing values, some ratings still need to be treated.

I used the median of the valid ratings to fill these gaps. This keeps the replacement values within the range of ratings already present in the dataset. The imputed values are estimates, not the original customers' ratings.

In [127]:
# Record the missing ratings before filling them
rating_missing_before = amazon_data_copy["rating"].isna().sum()

# Calculate the median from the valid ratings
rating_median = amazon_data_copy["rating"].median()

# Fill only the ratings that are currently missing
amazon_data_copy["rating"] = amazon_data_copy["rating"].fillna(rating_median)

# Check that the missing ratings have been handled
rating_missing_after = amazon_data_copy["rating"].isna().sum()

rating_missing_before, rating_median, rating_missing_after

(np.int64(31), 4.1, np.int64(0))

### Handling Missing Rating Counts

The "Rating Count" column contains numerical counts, but some original entries were blank while others contained the text "Not enough ratings".

For the records that were originally blank, I used the median of the available rating counts as an estimate. I kept the "Not enough ratings" cases missing because the original entry does not provide an exact count, and replacing it with the median would give the impression that the product had a known number of ratings.

This keeps the numerical data usable without inventing a specific count for those placeholder entries.

In [128]:
# Find rating counts that were genuinely blank in the original dataset
raw_blank_rating_count_indices = amazon_data.index[
    amazon_data["Rating Count"].isna()]

# Select missing counts that were blank originally, not converted from a text placeholder
rating_count_fill_mask = (
    amazon_data_copy["Rating Count"].isna()
    & amazon_data_copy.index.isin(raw_blank_rating_count_indices))

# Use a whole-number median because rating counts represent counts of ratings
rating_count_median = int(round(amazon_data_copy["Rating Count"].median()))

# Record how many original blanks will be filled
rating_count_filled = rating_count_fill_mask.sum()

# Fill only those original blanks
amazon_data_copy.loc[rating_count_fill_mask, "Rating Count"] = rating_count_median

rating_count_filled, rating_count_median, amazon_data_copy["Rating Count"].isna().sum()

(np.int64(19), 5195, np.int64(8))

### Missing Descriptions, Review Text and Links

I retained the remaining missing values in "about_product", "user_name", "review_title", "review_content", "IMG_LINK", and "product_link".

These fields contain descriptive text, reviewer information, or links that cannot be reliably recovered from the available data. Filling them with the most common text or creating replacement links would introduce information that may not be correct. I therefore kept these values missing rather than making unsupported assumptions or deleting otherwise useful product records.

In [129]:
# Check what is still missing after the imputation decisions
missing_report_final = pd.DataFrame({
    "Null Count": amazon_data_copy.isna().sum(),
    "Null Percentage": (
        amazon_data_copy.isna().sum() / len(amazon_data_copy) * 100
    ).round(2)})

missing_report_final[missing_report_final["Null Count"] > 0]

                Null Count  Null Percentage
Rating Count             8             0.55
about_product           14             0.97
user_name                1             0.07
review_title             6             0.41
review_content           4             0.28
IMG_LINK                11             0.76
product_link            11             0.76

## Outlier Detection

After cleaning the numerical fields and handling the missing values, I checked for potential outliers using the Interquartile Range (IQR) method.

I applied the check to the price, discount, rating, and rating-count columns. The purpose is to identify values that are unusually far from the middle of each distribution. A value flagged by this method is not automatically a mistake, so I will review the results before deciding whether to retain, cap, or remove any observations.

In [130]:
# Columns to check for potential outliers
numeric_columns = [
    "Discounted_Price (INR)",
    "actual_price",
    "discount_percentage",
    "rating",
    "Rating Count"]

def get_iqr_summary(series):
    values = series.dropna()

    q1 = values.quantile(0.25)
    q3 = values.quantile(0.75)
    iqr = q3 - q1

    lower_limit = q1 - 1.5 * iqr
    upper_limit = q3 + 1.5 * iqr

    outlier_count = (
        (values < lower_limit) | (values > upper_limit)
    ).sum()

    return pd.Series({
        "Q1": q1,
        "Q3": q3,
        "IQR": iqr,
        "Lower Limit": lower_limit,
        "Upper Limit": upper_limit,
        "Outlier Count": outlier_count})


outlier_report = pd.DataFrame({
    column: get_iqr_summary(amazon_data_copy[column])
    for column in numeric_columns
}).T

outlier_report.round(2)

,Q1,Q3,IQR,Lower Limit,Upper Limit,Outlier Count
Discounted_Price (INR),309.75,1999.00,1689.25,-2224.12,4532.88,210.0
actual_price,800.00,4222.50,3422.50,-4333.75,9356.25,209.0
discount_percentage,32.00,63.00,31.00,-14.50,109.50,0.0
rating,4.00,4.30,0.30,3.55,4.75,72.0
Rating Count,1198.25,17244.75,16046.50,-22871.50,41314.50,139.0

### Reviewing the Detected Outliers

The IQR check identified potential outliers in the price, rating, and rating-count columns. However, being outside the calculated limits does not automatically mean a value is incorrect.

I will review a few of the flagged records to see whether the values appear reasonable for the products involved. I will only change an outlier if there is evidence of a data-quality problem; otherwise, I will retain it rather than remove or cap a potentially valid observation.

In [131]:
# Review a few of the highest discounted prices flagged by the IQR check
discounted_price_outliers = amazon_data_copy.loc[
    amazon_data_copy["Discounted_Price (INR)"]
    > outlier_report.loc["Discounted_Price (INR)", "Upper Limit"],
    [
        "product_name",
        "Discounted_Price (INR)",
        "actual_price",
        "discount_percentage"
    ]
].sort_values("Discounted_Price (INR)", ascending=False).head()

discounted_price_outliers

,product_name,Discounted_Price (INR),actual_price,discount_percentage
758,Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...,77990.0,139900.0,44.0
573,OnePlus 163.8 cm (65 inches) U Series 4K LED S...,61999.0,69999.0,11.0
817,VU 164 cm (65 inches) The GloLED Series 4K Sma...,54990.0,85000.0,35.0
1202,LG 139 cm (55 inches) 4K Ultra HD Smart LED TV...,47990.0,79990.0,40.0
205,Samsung 138 cm (55 inches) Crystal 4K Neo Seri...,47990.0,70900.0,32.0

In [132]:
# Review a few of the highest actual prices flagged by the IQR check
actual_price_outliers = amazon_data_copy.loc[
    amazon_data_copy["actual_price"]
    > outlier_report.loc["actual_price", "Upper Limit"],
    [
        "product_name",
        "actual_price",
        "Discounted_Price (INR)",
        "discount_percentage"
    ]
].sort_values("actual_price", ascending=False).head()

actual_price_outliers

,product_name,actual_price,Discounted_Price (INR),discount_percentage
758,Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...,139900.0,77990.0,44.0
817,VU 164 cm (65 inches) The GloLED Series 4K Sma...,85000.0,54990.0,35.0
1202,LG 139 cm (55 inches) 4K Ultra HD Smart LED TV...,79990.0,47990.0,40.0
745,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,75990.0,42990.0,43.0
974,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",74999.0,37990.0,49.0

In [133]:
# Review ratings that fall outside the IQR limits
rating_outliers = amazon_data_copy.loc[
    (amazon_data_copy["rating"] < outlier_report.loc["rating", "Lower Limit"])
    |
    (amazon_data_copy["rating"] > outlier_report.loc["rating", "Upper Limit"]),
    ["product_name", "rating"]
].sort_values("rating")

rating_outliers

                                           product_name  rating
724   Khaitan ORFin Fan heater for Home and kitchen-...     2.0
259   Personal Size Blender, Portable Blender, Batte...     2.3
942   Green Tales Heat Seal Mini Food Sealer-Impulse...     2.6
1186  MR. BRAND Portable USB Juicer Electric USB Jui...     2.8
1243  IONIX Tap filter Multilayer | Activated Carbon...     2.9
...                                                 ...     ...
345   Swiffer Instant Electric Water Heater Faucet T...     4.8
635   Instant Pot Air Fryer, Vortex 2QT, Touch Contr...     4.8
337   Syncwire LTG to USB Cable for Fast Charging Co...     5.0
151   REDTECH USB-C to Lightning Cable 3.3FT, [Apple...     5.0
1429  Amazon Basics Wireless Mouse | 2.4 GHz Connect...     5.0

[72 rows x 2 columns]

In [134]:
# Review products with unusually high rating counts
rating_count_outliers = amazon_data_copy.loc[
    amazon_data_copy["Rating Count"]
    > outlier_report.loc["Rating Count", "Upper Limit"],
    ["product_name", "Rating Count", "rating"]
].sort_values("Rating Count", ascending=False).head()

rating_count_outliers

                                           product_name  Rating Count  rating
668   Amazon Basics High-Speed HDMI Cable, 6 Feet - ...      426973.0     4.4
555   AmazonBasics Flexible Premium HDMI Cable (Blac...      426973.0     4.4
85    Amazon Basics High-Speed HDMI Cable, 6 Feet (2...      426973.0     4.4
1151  AmazonBasics Flexible Premium HDMI Cable (Blac...      426972.0     4.4
1289  boAt Bassheads 100 in Ear Wired Earphones with...      363713.0     4.1

### Outlier Review

The IQR method flagged unusually high prices, some ratings outside the middle range, and products with high rating counts. After reviewing examples from these columns, I found that the extreme prices belonged to products such as large-screen televisions and air conditioners. These are expensive products, so their prices were not treated as errors simply because they exceeded the IQR limits.

The ratings flagged by the method were still within the valid 1–5 range, and the high rating counts appeared plausible for popular products. I therefore retained the flagged values instead of capping or deleting them. The earlier range checks remain important, since genuinely invalid values such as negative prices and ratings outside 1–5 were handled separately during cleaning.

### Final Data Type Correction

After the cleaning and missing-value treatments, I checked the column types one last time. I converted identifiers and descriptive fields to a consistent string type, kept prices, discounts and ratings numeric, and used an integer type for rating counts because they represent whole numbers of ratings.

This final step makes the columns more suitable for later analysis while allowing missing values to remain in the fields where I deliberately retained them.

In [135]:
# Keep identifiers and descriptive fields in a consistent text format
text_columns = [
    "product_id",
    "product_name",
    "category",
    "about_product",
    "user_id",
    "user_name",
    "review_id",
    "review_title",
    "review_content",
    "IMG_LINK",
    "product_link"
]

amazon_data_copy[text_columns] = (
    amazon_data_copy[text_columns].astype("string"))

In [136]:
# Keep prices, discounts and ratings in a numeric type that supports missing values
numeric_float_columns = [
    "Discounted_Price (INR)",
    "actual_price",
    "discount_percentage",
    "rating"
]

amazon_data_copy[numeric_float_columns] = (
    amazon_data_copy[numeric_float_columns].astype("Float64")
)

In [137]:
# Store rating counts as whole numbers while preserving missing entries
amazon_data_copy["Rating Count"] = (
    amazon_data_copy["Rating Count"].round().astype("Int64")
)

In [138]:
amazon_data_copy.dtypes

product_id                string[python]
product_name              string[python]
category                  string[python]
Discounted_Price (INR)           Float64
actual_price                     Float64
discount_percentage              Float64
rating                           Float64
Rating Count                       Int64
about_product             string[python]
user_id                   string[python]
user_name                 string[python]
review_id                 string[python]
review_title              string[python]
review_content            string[python]
IMG_LINK                  string[python]
product_link              string[python]
dtype: object

In [139]:
# Check which missing values remain after the cleaning decisions
missing_report_final = pd.DataFrame({
    "Null Count": amazon_data_copy.isna().sum(),
    "Null Percentage": (
        amazon_data_copy.isna().sum() / len(amazon_data_copy) * 100
    ).round(2)
})

missing_report_final[missing_report_final["Null Count"] > 0]

                Null Count  Null Percentage
Rating Count             8             0.55
about_product           14             0.97
user_name                1             0.07
review_title             6             0.41
review_content           4             0.28
IMG_LINK                11             0.76
product_link            11             0.76

## Final Validation

After completing the cleaning and missing-data treatments, I checked the dataset again to confirm that the main quality issues identified at the beginning had been addressed.

I checked the remaining row count, duplicate records, completely blank rows, and the valid ranges for prices, discounts, ratings, and rating counts. The remaining missing values were also reviewed to make sure they reflect the decisions documented earlier rather than untreated formatting problems.

In [140]:
# Check the main quality rules after cleaning
final_checks = pd.Series({
    "Rows remaining": len(amazon_data_copy),
    "Total missing cells": int(amazon_data_copy.isna().sum().sum()),
    "Exact duplicate rows": int(amazon_data_copy.duplicated().sum()),
    "Completely blank rows": int(amazon_data_copy.isna().all(axis=1).sum()),
    "Non-positive discounted prices": int(
        (amazon_data_copy["Discounted_Price (INR)"] <= 0).sum()
    ),
    "Non-positive actual prices": int(
        (amazon_data_copy["actual_price"] <= 0).sum()
    ),
    "Discounts outside 0–100": int(
        (
            (amazon_data_copy["discount_percentage"] < 0) |
            (amazon_data_copy["discount_percentage"] > 100)
        ).sum()
    ),
    "Ratings outside 1–5": int(
        (
            (amazon_data_copy["rating"] < 1) |
            (amazon_data_copy["rating"] > 5)
        ).sum()
    ),
    "Negative rating counts": int(
        (amazon_data_copy["Rating Count"] < 0).sum()
    )
})

final_checks

Rows remaining                    1448
Total missing cells                 55
Exact duplicate rows                 2
Completely blank rows                0
Non-positive discounted prices       0
Non-positive actual prices           0
Discounts outside 0–100              0
Ratings outside 1–5                  0
Negative rating counts               0
dtype: int64

## Before and After Cleaning

I compared the raw dataset with the cleaned version to measure the changes made during the cleaning process. The comparison covers row count, missing values, duplicate records, completely blank rows, and data type accuracy.

The original dataset was retained throughout the process so that the comparison reflects the actual changes rather than estimates of the starting condition.

In [141]:
# Use the intended data types as the reference for the comparison
target_dtypes = {
    "product_id": "string",
    "product_name": "string",
    "category": "string",
    "Discounted_Price (INR)": "Float64",
    "actual_price": "Float64",
    "discount_percentage": "Float64",
    "rating": "Float64",
    "Rating Count": "Int64",
    "about_product": "string",
    "user_id": "string",
    "user_name": "string",
    "review_id": "string",
    "review_title": "string",
    "review_content": "string",
    "IMG_LINK": "string",
    "product_link": "string"
}


# Align the original column names with the cleaned schema for a fair comparison
raw_for_dtype_check = amazon_data.copy()
raw_for_dtype_check.columns = raw_for_dtype_check.columns.str.strip()

before_dtype_matches = sum(
    str(raw_for_dtype_check[column].dtype) == expected_dtype
    for column, expected_dtype in target_dtypes.items()
)

after_dtype_matches = sum(
    str(amazon_data_copy[column].dtype) == expected_dtype
    for column, expected_dtype in target_dtypes.items()
)

comparison = pd.DataFrame({
    "Metric": [
        "Row count",
        "Total missing cells",
        "Exact duplicate rows",
        "Completely blank rows",
        "Columns matching the exact target dtype",
        "Target dtype compliance (%)"
    ],
    "Before Cleaning": [
        len(amazon_data),
        int(amazon_data.isna().sum().sum()),
        int(amazon_data.duplicated().sum()),
        int(amazon_data.isna().all(axis=1).sum()),
        before_dtype_matches,
        round(before_dtype_matches / len(target_dtypes) * 100, 2)
    ],
    "After Cleaning": [
        len(amazon_data_copy),
        int(amazon_data_copy.isna().sum().sum()),
        int(amazon_data_copy.duplicated().sum()),
        int(amazon_data_copy.isna().all(axis=1).sum()),
        after_dtype_matches,
        round(after_dtype_matches / len(target_dtypes) * 100, 2)
    ]
})

comparison

                                    Metric  Before Cleaning  After Cleaning
0                                Row count           1495.0          1448.0
1                      Total missing cells            286.0            55.0
2                     Exact duplicate rows             13.0             2.0
3                    Completely blank rows              8.0             0.0
4  Columns matching the exact target dtype              0.0            16.0
5              Target dtype compliance (%)              0.0           100.0

In [142]:
duplicate_rows = amazon_data_copy[
    amazon_data_copy.duplicated(keep=False)
]

duplicate_rows

,product_id,product_name,category,Discounted_Price (INR),actual_price,discount_percentage,rating,Rating Count,about_product,user_id,user_name,review_id,review_title,review_content,IMG_LINK,product_link
16,B00P93X2H6,Classmate Pulse Spiral Notebook - 240 mm x 180...,OfficeProducts|OfficePaperProducts|Paper|Stati...,67.0,75.0,11.0,4.1,1269,The cover design of the notebook is subject to...,"AH6NK74TCKWVMLPVFEC44ZLT546Q,AEUNLUIL7UEDSBOHD...","Nafisa Nehar,Narinder K.,Mayank,Harsh Raj,Dr.G...","R3QLOAFS794JE2,R3N8H6JX73IGQM,RR2G573NOMISE,R1...","it's nice. simple and easy.,It's good but I or...",I liked because it was aesthetically pleasing....,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Classmate-Pulse-Spiral-N...
193,B00P93X2H6,Classmate Pulse Spiral Notebook - 240 mm x 180...,OfficeProducts|OfficePaperProducts|Paper|Stati...,67.0,75.0,11.0,4.1,1269,The cover design of the notebook is subject to...,"AH6NK74TCKWVMLPVFEC44ZLT546Q,AEUNLUIL7UEDSBOHD...","Nafisa Nehar,Narinder K.,Mayank,Harsh Raj,Dr.G...","R3QLOAFS794JE2,R3N8H6JX73IGQM,RR2G573NOMISE,R1...","it's nice. simple and easy.,It's good but I or...",I liked because it was aesthetically pleasing....,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Classmate-Pulse-Spiral-N...
373,B08H6CZSHT,Philips EasySpeed Plus Steam Iron GC2145/20-22...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",2903.0,3295.0,12.0,4.3,2299,Triple Precision Tip and 360 degree swivel cor...,"AEBZ2HAXFK35IM72RWPADC7VH3EA,AFYJKU3CYIDTCWXSR...","M L.,SIVAKUMAR,Sriram,Kalpana singh,Shaikh Noo...","RK56D57RLGNG7,R3SZTBONWK6EEB,RW0XZ8GFEVSHT,R1O...","Steam irom,Good,Value for money,Amazing produc...","Light weight steam iron is very useful,Very go...",https://m.media-amazon.com/images/I/41iBNm2ivF...,https://www.amazon.in/EasySpeed-GC2145-Resista...
1235,B08H6CZSHT,Philips EasySpeed Plus Steam Iron GC2145/20-22...,"Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cle...",2903.0,3295.0,12.0,4.3,2299,Triple Precision Tip and 360 degree swivel cor...,"AEBZ2HAXFK35IM72RWPADC7VH3EA,AFYJKU3CYIDTCWXSR...","M L.,SIVAKUMAR,Sriram,Kalpana singh,Shaikh Noo...","RK56D57RLGNG7,R3SZTBONWK6EEB,RW0XZ8GFEVSHT,R1O...","Steam irom,Good,Value for money,Amazing produc...","Light weight steam iron is very useful,Very go...",https://m.media-amazon.com/images/I/41iBNm2ivF...,https://www.amazon.in/EasySpeed-GC2145-Resista...

In [143]:
duplicates_removed_at_final_check = amazon_data_copy.duplicated().sum()

amazon_data_copy = amazon_data_copy.drop_duplicates()

duplicates_removed_at_final_check, amazon_data_copy.duplicated().sum()

(np.int64(2), np.int64(0))

### Final Duplicate Check

I checked for exact duplicates again after standardisation and imputation.
Two repeated rows were identified at this stage and removed before producing
the final validation results and comparison table.

Cleaning can make previously different records identical. I treated these
fully identical records as duplicates and kept the first occurrence.

In [144]:
amazon_data_copy.to_csv(
    "amazon_products_reviews_cleaned.csv",
    index=False
)

cleaned_data_check = pd.read_csv(
    "amazon_products_reviews_cleaned.csv"
)

cleaned_data_check.shape

(1446, 16)